// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ObjectsColumns holds the columns for the "objects" table.
	ObjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "package", Type: field.TypeString},
		{Name: "type", Type: field.TypeInt8},
		{Name: "hash", Type: field.TypeString},
		{Name: "content", Type: field.TypeBytes},
	}
	// ObjectsTable holds the schema information for the "objects" table.
	ObjectsTable = &schema.Table{
		Name:       "objects",
		Columns:    ObjectsColumns,
		PrimaryKey: []*schema.Column{ObjectsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "object_package_hash",
				Unique:  true,
				Columns: []*schema.Column{ObjectsColumns[1], ObjectsColumns[3]},
			},
		},
	}
	// ReferencesColumns holds the columns for the "references" table.
	ReferencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "package", Type: field.TypeString},
		{Name: "ref", Type: field.TypeString},
		{Name: "hash", Type: field.TypeString},
	}
	// ReferencesTable holds the schema information for the "references" table.
	ReferencesTable = &schema.Table{
		Name:       "references",
		Columns:    ReferencesColumns,
		PrimaryKey: []*schema.Column{ReferencesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "reference_package_ref",
				Unique:  true,
				Columns: []*schema.Column{ReferencesColumns[1], ReferencesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ObjectsTable,
		ReferencesTable,
	}
)

func init() {
}
