// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Object is the predicate function for object builders.
type Object func(*sql.Selector)

// Reference is the predicate function for reference builders.
type Reference func(*sql.Selector)
