---
resources:
  - name: grm
    type: git
    icon: github
    source:
      uri: git@github.com:Jameslikestea/grm.git
      private_key: ((grm_secrets.ssh_key))
      branch: ((BRANCH))

  - name: golang1.17
    type: registry-image
    source:
      repository: golang
      tag: 1.17

  - name: golang1.16
    type: registry-image
    source:
      repository: golang
      tag: 1.16

jobs:
  - name: test_1.17
    plan:
      - get: grm
        trigger: true
      - get: golang1.17
      - task: test
        image: golang1.17
        config:
          platform: linux
          inputs:
            - name: grm
          run:
            dir: grm
            path: go
            args:
              - test
              - ./...
  - name: test_1.16
    plan:
      - get: grm
        trigger: true
      - get: golang1.16
      - task: test
        image: golang1.16
        config:
          platform: linux
          inputs:
            - name: grm
          run:
            dir: grm
            path: go
            args:
              - test
              - ./...
