// Code generated by entc, DO NOT EDIT.

package reference

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Jameslikestea/grm/internal/storage/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Package applies equality check predicate on the "package" field. It's identical to PackageEQ.
func Package(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPackage), v))
	})
}

// Ref applies equality check predicate on the "ref" field. It's identical to RefEQ.
func Ref(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRef), v))
	})
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHash), v))
	})
}

// PackageEQ applies the EQ predicate on the "package" field.
func PackageEQ(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPackage), v))
	})
}

// PackageNEQ applies the NEQ predicate on the "package" field.
func PackageNEQ(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPackage), v))
	})
}

// PackageIn applies the In predicate on the "package" field.
func PackageIn(vs ...string) predicate.Reference {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Reference(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPackage), v...))
	})
}

// PackageNotIn applies the NotIn predicate on the "package" field.
func PackageNotIn(vs ...string) predicate.Reference {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Reference(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPackage), v...))
	})
}

// PackageGT applies the GT predicate on the "package" field.
func PackageGT(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPackage), v))
	})
}

// PackageGTE applies the GTE predicate on the "package" field.
func PackageGTE(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPackage), v))
	})
}

// PackageLT applies the LT predicate on the "package" field.
func PackageLT(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPackage), v))
	})
}

// PackageLTE applies the LTE predicate on the "package" field.
func PackageLTE(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPackage), v))
	})
}

// PackageContains applies the Contains predicate on the "package" field.
func PackageContains(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPackage), v))
	})
}

// PackageHasPrefix applies the HasPrefix predicate on the "package" field.
func PackageHasPrefix(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPackage), v))
	})
}

// PackageHasSuffix applies the HasSuffix predicate on the "package" field.
func PackageHasSuffix(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPackage), v))
	})
}

// PackageEqualFold applies the EqualFold predicate on the "package" field.
func PackageEqualFold(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPackage), v))
	})
}

// PackageContainsFold applies the ContainsFold predicate on the "package" field.
func PackageContainsFold(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPackage), v))
	})
}

// RefEQ applies the EQ predicate on the "ref" field.
func RefEQ(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRef), v))
	})
}

// RefNEQ applies the NEQ predicate on the "ref" field.
func RefNEQ(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRef), v))
	})
}

// RefIn applies the In predicate on the "ref" field.
func RefIn(vs ...string) predicate.Reference {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Reference(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRef), v...))
	})
}

// RefNotIn applies the NotIn predicate on the "ref" field.
func RefNotIn(vs ...string) predicate.Reference {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Reference(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRef), v...))
	})
}

// RefGT applies the GT predicate on the "ref" field.
func RefGT(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRef), v))
	})
}

// RefGTE applies the GTE predicate on the "ref" field.
func RefGTE(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRef), v))
	})
}

// RefLT applies the LT predicate on the "ref" field.
func RefLT(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRef), v))
	})
}

// RefLTE applies the LTE predicate on the "ref" field.
func RefLTE(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRef), v))
	})
}

// RefContains applies the Contains predicate on the "ref" field.
func RefContains(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldRef), v))
	})
}

// RefHasPrefix applies the HasPrefix predicate on the "ref" field.
func RefHasPrefix(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldRef), v))
	})
}

// RefHasSuffix applies the HasSuffix predicate on the "ref" field.
func RefHasSuffix(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldRef), v))
	})
}

// RefEqualFold applies the EqualFold predicate on the "ref" field.
func RefEqualFold(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldRef), v))
	})
}

// RefContainsFold applies the ContainsFold predicate on the "ref" field.
func RefContainsFold(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldRef), v))
	})
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldHash), v))
	})
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldHash), v))
	})
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.Reference {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Reference(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldHash), v...))
	})
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.Reference {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Reference(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldHash), v...))
	})
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldHash), v))
	})
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldHash), v))
	})
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldHash), v))
	})
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldHash), v))
	})
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldHash), v))
	})
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldHash), v))
	})
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldHash), v))
	})
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldHash), v))
	})
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldHash), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Reference) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Reference) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Reference) predicate.Reference {
	return predicate.Reference(func(s *sql.Selector) {
		p(s.Not())
	})
}
